import { ArrowRight, CarFront, Check, MessageCircle, Phone, Wrench } from "lucide-react";
import { Footer, Header, MobileBar } from "@/components/site-shell";
import { Lang, PHONE_DISPLAY, PHONE_LINK, WHATSAPP_LINK } from "@/lib/site-data";

const text = {
  en: { eye: "Simple help, no runaround", h: "How it works", p: "One call gets the process moving. We explain the price and the practical next step before the work starts.", steps: [["Call or WhatsApp", "Send your location, vehicle details and what happened. For outer areas, we confirm the call-out fee before travelling."], ["We come to you", "The equipped 4WD attends your home, workplace, roadside location or 4WD track. Response time depends on the current job and distance."], ["Repair or recover", "We repair on site when practical, recover the vehicle when needed, or use the workshop and hoist for major work."], ["Pay when the job is done", "Pay by card, cash, bank transfer or Afterpay. Workmanship is covered for six months, with supplier warranties on parts."]], mobileH: "Mobile first. Full workshop behind us.", mobileP: "Most diagnostics, servicing and suitable repairs happen where the vehicle is. Engines, transmissions, clutches and underbody work can move to Unit 3/3 Toohey St, Cairns.", cta: "Tell us what happened" },
  es: { eye: "Ayuda sencilla, sin vueltas", h: "Cómo funciona", p: "Una llamada pone todo en marcha. Explicamos el precio y el siguiente paso antes de empezar.", steps: [["Llama o escribe", "Envía ubicación, vehículo y qué ha ocurrido. Para zonas lejanas, confirmamos el desplazamiento antes de salir."], ["Vamos hasta ti", "El 4x4 equipado llega a casa, trabajo, carretera o pista 4x4. El tiempo depende del trabajo en curso y la distancia."], ["Reparamos o rescatamos", "Reparamos allí cuando sea posible, recuperamos el vehículo o utilizamos el taller y elevador para trabajos mayores."], ["Paga al terminar", "Tarjeta, efectivo, transferencia o Afterpay. Seis meses de garantía de mano de obra y garantía del proveedor en piezas."]], mobileH: "Primero móvil. Taller completo detrás.", mobileP: "La mayoría de diagnósticos y reparaciones se hacen donde está el vehículo. Motores, transmisiones, embragues y bajos pasan a Unit 3/3 Toohey St, Cairns.", cta: "Cuéntanos qué ha pasado" },
  fr: { eye: "Une aide simple, sans détour", h: "Comment ça marche", p: "Un appel suffit. Nous expliquons le prix et la suite avant de commencer.", steps: [["Appelez ou écrivez", "Envoyez votre position, le véhicule et le problème. Pour les zones éloignées, nous confirmons les frais avant le départ."], ["On vient à vous", "Le 4x4 équipé intervient à domicile, au travail, sur route ou piste 4x4. Le délai dépend de l’intervention en cours et de la distance."], ["Réparation ou dépannage", "Nous réparons sur place si possible, récupérons le véhicule ou utilisons l’atelier et le pont pour les gros travaux."], ["Payez à la fin", "Carte, espèces, virement ou Afterpay. Garantie main-d’œuvre six mois et garantie fournisseur sur les pièces."]], mobileH: "Mobile d’abord. Atelier complet en soutien.", mobileP: "La plupart des diagnostics et réparations se font sur place. Moteurs, transmissions, embrayages et dessous de caisse passent à l’atelier, Unit 3/3 Toohey St, Cairns.", cta: "Décrivez le problème" },
} satisfies Record<Lang, any>;

export function ProcessPage({ lang }: { lang: Lang }) {
  const c = text[lang];
  const stepIcons = [MessageCircle, CarFront, Wrench, Check];
  return <><Header lang={lang} page="process" /><main>
    <section className="areas-hero"><div className="wrap"><p className="eyebrow">{c.eye}</p><h1>{c.h}</h1><p>{c.p}</p><div className="cta-row"><a className="btn primary" href={PHONE_LINK}><Phone size={18} />{PHONE_DISPLAY}</a><a className="btn secondary on-dark" href={WHATSAPP_LINK}><MessageCircle size={18} />WhatsApp</a></div></div></section>
    <section className="section"><div className="wrap process-page-grid">{c.steps.map((s: string[], i: number) => { const Icon = stepIcons[i]; return <article key={s[0]}><span>{String(i + 1).padStart(2, "0")}</span><Icon /><h2>{s[0]}</h2><p>{s[1]}</p></article>; })}</div></section>
    <section className="workshop process-workshop"><div className="workshop-image brand-wall"><span>MOBILE</span><span>4WD</span><span>WORKSHOP</span><span>HOIST</span></div><div className="workshop-copy"><h2>{c.mobileH}</h2><p>{c.mobileP}</p><a className="btn primary" href={WHATSAPP_LINK}>{c.cta}<ArrowRight size={17} /></a></div></section>
  </main><Footer lang={lang} /><MobileBar lang={lang} /></>;
}
